<?php
	$config['user_plugins_default'] = array(
		'carddav',
		'contextmenu',
		'identicon',
		'keyboard_shortcuts',
		'managesieve',
		'message_highlight',
		'special_folders',
		'taskconfig',
		'taskwatermark',
		// 'autocomplete',
		// 'calendar',
		// 'contacts_photo',
		// 'ident_switch',
		// 'identity_select',
		// 'imap_notes',
		// 'markasjunk',
		// 'unread_favicon',
	);
	$config['user_plugins_blacklist'] = array(
		'acl',
		'additional_message_headers',
		'autologon',
		'database_attachments',
		'debug_logger',
		'example_addressbook',
		'help',
		'http_authentication',
		'jqueryui',
		'krb_authentication',
		'newmail_notifier',
		'new_user_dialog',
		'new_user_identity',
		'password',
		'redundant_attachments',
		'squirrelmail_usercopy',
		'subscriptions_option',
		'userinfo',
		'virtuser_file',
		'virtuser_query',

		'persistent_login',
		'pop3fetcher'
		// 'acl', 'additional_message_headers', 'archive', 'attachment_reminder', 'autologon', 'database_attachments',
		// 'debug_logger', 'emoticons', 'enigma', 'example_addressbook', 'filesystem_attachments', 'help',
		// 'hide_blockquote', 'http_authentication', 'identicon', 'identity_select', 'jqueryui', 'krb_authentication',
		// 'managesieve', 'markasjunk', 'newmail_notifier', 'new_user_dialog', 'new_user_identity', 'password',
		// 'redundant_attachments', 'show_additional_headers', 'squirrelmail_usercopy', 'subscriptions_option',
		// 'userinfo', 'vcard_attachments', 'virtuser_file', 'virtuser_query', 'zipdownload'
	);